"""pull.py - The Escalation Cost data layer: pull, hash, document.

Manifest: DESIGN.md Section 14 (pin 74c73ea165a7363c6714fe803fbe76b1 at freeze;
including the dated 2026-07-13 amendment: panel member A31SIS primary metals,
A25SIS retained as audit-trail non-member documenting the source mislabel).

Rules honored here:
- Fresh pulls only; no local variant trusted by filename.
- SOURCES.md is GENERATED by this script; never hand-edit (fix the generator).
- Raw data lives in the git-ignored project-local store; never committed.
- Honest failure capture: a failed pull with a stale file on disk is hashed
  and FLAGGED, never silently passed.
- The 17-sector map below is FROZEN at first hash and never edited after.

Usage:
  python data\\pull.py            pull everything, hash, write SOURCES.md
  python data\\pull.py --verify   re-hash files on disk, no network
  python data\\pull.py --only ID  pull a single registry id (no SOURCES.md write)
"""

from __future__ import annotations

import hashlib
import os
import sys
from datetime import date
from pathlib import Path

import requests

STORE = Path(os.environ.get(
    "EC_STORE", r"C:\Users\jaek9\Documents\LaggingTruth\The-Escalation-Cost"))
RAW = STORE / "raw"
SOURCES_MD = Path(__file__).resolve().parent / "SOURCES.md"
UA = {"User-Agent": "EscalationCost-research/1.0 (jae@laggingtruth.com)"}
TIMEOUT = 180
FRED_CSV = "https://fred.stlouisfed.org/graph/fredgraph.csv?id={sid}"

FRED_TOL = ("A replicator's fresh pull may differ on: latest-month vintage "
            "(new releases + revisions to recent months). Absorbed by: all "
            "experiments use windows ending at the frozen pull date; DESIGN "
            "notes extension-to-latest is not a spec change.")

# ---------------------------------------------------------------------------
# FROZEN 17-SECTOR MAP (DESIGN Section 14 + dated amendment 2026-07-13).
# Titles FRED-verified 2026-07-13 (none frozen on a guess). NEVER EDIT after
# first hash; changes require a dated DESIGN amendment and are append-only.
# role: member-mfg | member-wholesale | member-retail | aux (non-member)
# ---------------------------------------------------------------------------
SECTOR_MAP = [
    ("AMTMIS", "member-mfg", "Total Manufacturing I/S"),
    ("AMDMIS", "member-mfg", "Durable Goods I/S"),
    ("AMNMIS", "member-mfg", "Nondurable Goods I/S"),
    ("A34SIS", "member-mfg", "Computers and Electronic Products I/S"),
    ("A35SIS", "member-mfg", "Electrical Equipment, Appliances and Components I/S"),
    ("A36SIS", "member-mfg", "Transportation Equipment I/S"),
    ("A31SIS", "member-mfg", "Primary Metals I/S [2026-07-13 amendment]"),
    ("R4231IM163SCEN", "member-wholesale", "Wholesale Motor Vehicles I/S"),
    ("R4232IM163SCEN", "member-wholesale", "Wholesale Furniture I/S"),
    ("R4233IM163SCEN", "member-wholesale", "Wholesale Lumber/Construction I/S"),
    ("R4234IM163SCEN", "member-wholesale", "Wholesale Professional/Commercial Equipment I/S"),
    ("R4236IM163SCEN", "member-wholesale", "Wholesale Electrical/Electronics I/S"),
    ("R4238IM163SCEN", "member-wholesale", "Wholesale Machinery I/S"),
    ("R423IRM163SCEN", "member-wholesale", "Wholesale Total Durables I/S"),
    ("MRTSIR441USS", "member-retail", "Retail Motor Vehicle Dealers I/S"),
    ("MRTSIR444USS", "member-retail", "Retail Building Materials I/S"),
    ("MRTSIR452USS", "member-retail", "Retail General Merchandise I/S"),
    # --- auxiliary, non-member ---
    ("A25SIS", "aux", "Chemical Products I/S [AUDIT TRAIL: source-defect series - "
     "mislabeled 'primary metals' in the source; see DESIGN amendment 2026-07-13]"),
    ("ANAPTI", "aux", "Aerospace: total inventories (ratio numerator)"),
    ("ANAPVS", "aux", "Aerospace: value of shipments (ratio denominator)"),
    ("R4235IM163SCEN", "aux", "Wholesale Metals/Minerals I/S (manifest, non-member)"),
    ("R4237IM163SCEN", "aux", "Wholesale Hardware/Plumbing I/S (manifest, non-member)"),
    ("R4239IM163SCEN", "aux", "Wholesale Miscellaneous Durables I/S (manifest, non-member)"),
]

MEMBER_COUNT = sum(1 for _, role, _ in SECTOR_MAP if role.startswith("member"))
assert MEMBER_COUNT == 17, f"frozen map must have exactly 17 members, got {MEMBER_COUNT}"


def _fred(sid: str, used_by: str, note: str = "") -> dict:
    return dict(id=f"fred_{sid}", kind="fred", sid=sid,
                fname=f"fred_{sid}.csv", vendor="FRED (US Census / Fed)",
                symbol=sid, freq="monthly SA", used_by=used_by,
                tol=FRED_TOL, note=note)


SOURCES = (
    # Panel members + aux (order follows the frozen map)
    [_fred(sid, "E1 E2 E3 E5 (panel)" if role.startswith("member")
           else "audit/aux per manifest")
     for sid, role, _ in SECTOR_MAP]
    + [
        # Aggregates + activity context (manifest panel block)
        _fred("ISRATIO", "aggregate context"),
        _fred("MNFCTRIRSA", "aggregate context"),
        _fred("AMTMNO", "activity context"),
        _fred("AMTMVS", "activity context"),
        _fred("AMTMTI", "activity context"),
        _fred("DGORDER", "activity context"),
        _fred("ANDENO", "activity context"),
        # Semiconductors (E6)
        _fred("CAPUTLG3344S", "E6"),
        _fred("IPG3344S", "E6"),
        # Sovereign (E10)
        dict(id="e10_jst_r6", kind="http",
             url="https://www.macrohistory.net/app/download/9834512469/JSTdatasetR6.xlsx",
             fname="JSTdatasetR6.dta", vendor="JST Macrohistory (Release 6)",
             symbol="18 countries, 1870-2020; server delivers a Stata .dta "
                    "despite the .xlsx URL name - read with pandas.read_stata "
                    "(carried from the Measurement Trap pull, verified again "
                    "2026-07-13)",
             freq="annual", used_by="E10",
             tol="Fixed historical release; a replicator's pull should be "
                 "byte-identical. Mirror data.macrohistory.net may serve the "
                 "same content at a different URL."),
        # Unemployment insurance (E11)
        dict(id="e11_eta539", kind="http",
             url="https://oui.doleta.gov/unemploy/csv/ar539.csv",
             fname="eta539_ar539.csv", vendor="US DOL ETA",
             symbol="ETA 539 weekly claims, all jurisdictions, full history",
             freq="weekly", used_by="E11",
             tol="Rolling file - new report weeks append and recent weeks "
                 "revise. Absorbed by: E11 windows end at the frozen pull "
                 "date; quarterly aggregation smooths late revisions."),
        # Firm-level illustration - deferred-conditional per manifest
        dict(id="edgar_wmt_tgt", kind="deferred",
             fname="(not pulled)", vendor="SEC EDGAR XBRL",
             symbol="Walmart + Target I/S, 40 quarterly filings FY2020-FY2025",
             freq="quarterly", used_by="companion illustration only",
             tol="n/a until promoted",
             note="Deferred-conditional per manifest: companion-section "
                  "illustration, non-load-bearing; pulled and hashed only if "
                  "a committed analysis uses it (promotion = dated DESIGN "
                  "amendment)."),
    ]
    # --- E8 pricing artifacts (DESIGN Section 11 amendment 2026-07-16e) ---
    # NOT pulled. These are the SOURCE's own committed simulation outputs,
    # produced by the pricing code vendored at analysis/vendor/ and cleared on
    # all seven CIC classes (DESIGN 2026-07-16c). E8 is an ANALYSIS of these
    # artifacts rather than a re-execution (16e), so they are E8's DATA and the
    # contract requires them hashed here.
    #
    # kind="local" hashes in place and NEVER fetches: there is no upstream to
    # re-pull from and a "fresh pull" is meaningless for a fixed artifact. That
    # makes them the one input class for which --verify and a normal run are the
    # same operation, which is the correct behaviour, not a shortcut.
    #
    # The primary (validation_50seed) carries 1,800 raw trial records. Every E8
    # finding to date was computed against THESE EXACT BYTES: CIC-1 (all five
    # published figures reproduce at 13-21 sigma), DISC-03 (+13.01 formula
    # contribution vs the +10141.86 headline it is credited with), DISC-04 (the
    # two "identical" environments are one no-shift control under two names), and
    # the Claim A bound [-29.17, +55.19]. The hash pins the evidence; it is not a
    # formality.
    + [
        dict(id="phase27_validation_50seed", kind="local",
             fname="phase27/aggregated_phase27_validation_50seed.json",
             vendor="in-house (source's Phase 2.7 run, 2026-04-29)",
             symbol="aggregated_phase27_validation_50seed.json",
             freq="1,800 trials (9 envs x 4 scenarios x 50 seeds)",
             used_by="E8 primary (Claim A + Claim B)",
             tol=("None. A fixed artifact, not a live series: a replicator gets "
                  "these exact bytes or a different file. Regenerating it from "
                  "the vendored code is deterministic but costs ~16h "
                  "single-machine (19.04 s/trial, measured)."),
             note=("The source's own committed output. Its code clears all seven "
                   "CIC classes; its five published per-period figures recompute "
                   "from these raw records to under one unit. E8 analyses it "
                   "rather than re-running it (16e): Claim B is already resolved "
                   "at 13-21 sigma here, and Claim A's finding is a BOUND these "
                   "50 seeds already carry.")),
        dict(id="phase27_capsweep_18x", kind="local",
             fname="phase27/aggregated_phase27_capsweep_18x.json",
             vendor="in-house (source's Phase 2.7 capacity sweep, 2026-04-30)",
             symbol="aggregated_phase27_capsweep_18x.json",
             freq="1,800 trials @ 1.8x capacity",
             used_by="E8 robustness (capacity leg)",
             tol="None. Fixed artifact.", note=None),
        dict(id="phase27_capsweep_24x", kind="local",
             fname="phase27/aggregated_phase27_capsweep_24x.json",
             vendor="in-house (source's Phase 2.7 capacity sweep, 2026-04-30)",
             symbol="aggregated_phase27_capsweep_24x.json",
             freq="1,800 trials @ 2.4x capacity",
             used_by="E8 robustness (capacity leg)",
             tol="None. Fixed artifact.", note=None),
        dict(id="phase27_capsweep_30x", kind="local",
             fname="phase27/aggregated_phase27_capsweep_30x.json",
             vendor="in-house (source's Phase 2.7 capacity sweep, 2026-04-30)",
             symbol="aggregated_phase27_capsweep_30x.json",
             freq="1,800 trials @ 3.0x capacity",
             used_by="E8 robustness (capacity leg)",
             tol="None. Fixed artifact.", note=None),
        dict(id="phase27_elasticity_05", kind="local",
             fname="phase27/aggregated_phase27_elasticity_05.json",
             vendor="in-house (source's Phase 2.7 elasticity sweep, 2026-04-30)",
             symbol="aggregated_phase27_elasticity_05.json",
             freq="1,800 trials @ elasticity 0.5",
             used_by="E8 robustness (elasticity leg)",
             tol="None. Fixed artifact.", note=None),
        dict(id="phase27_elasticity_30", kind="local",
             fname="phase27/aggregated_phase27_elasticity_30.json",
             vendor="in-house (source's Phase 2.7 elasticity sweep, 2026-04-30)",
             symbol="aggregated_phase27_elasticity_30.json",
             freq="1,800 trials @ elasticity 3.0",
             used_by="E8 robustness (elasticity leg)",
             tol="None. Fixed artifact.", note=None),
        dict(id="phase27_hysteresis_20seed", kind="local",
             fname="phase27/phase2_7_hysteresis_results.json",
             vendor="in-house (source's Phase 2.7 hysteresis sweep, 2026-05-01)",
             symbol="phase2_7_hysteresis_results.json",
             freq="320 trials (2 envs x 2 scenarios x 4 intensities x 20 seeds)",
             used_by="E9 fidelity target (spec-derived re-implementation cross-check)",
             tol="None. Fixed artifact.",
             note=("The source's committed hysteresis output, seeds 2000-2019. "
                   "All four Appendix F hysteresis numbers recompute from these "
                   "records exactly (+8401.30/+5855.08/-540.58/-3320.45; "
                   "retention 69.7%). E9 re-implements the hysteresis layer "
                   "from specification (DESIGN Section 12 amendment 2026-07-16) "
                   "and must reproduce these cells per the pre-registered "
                   "fidelity tiers; this artifact is the CROSS-CHECK TARGET, "
                   "not the evidence - the evidence is our own run.")),
    ]
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(url: str) -> bytes:
    r = requests.get(url, headers=UA, timeout=TIMEOUT)
    r.raise_for_status()
    return r.content


def pull_one(src: dict, verify_only: bool) -> dict:
    rec = dict(src)
    if src["kind"] == "deferred":
        rec["status"] = "DEFERRED (conditional)"
        rec["store_path"] = "-"
        return rec
    dest = RAW / src["fname"]
    rec["store_path"] = str(dest)
    try:
        # kind="local" is never fetched: it is a fixed artifact already in the
        # store, with no upstream to pull from. It is hashed in place, and a
        # missing file is a hard FAILED - never silently skipped.
        if not verify_only and src["kind"] != "local":
            if src["kind"] == "fred":
                data = fetch(FRED_CSV.format(sid=src["sid"]))
            elif src["kind"] == "http":
                data = fetch(src["url"])
            else:
                raise ValueError(f"unknown kind {src['kind']}")
            if len(data) < 200:
                raise ValueError(f"suspiciously small response ({len(data)} bytes)")
            dest.write_bytes(data)
        if dest.exists():
            rec["sha256"] = sha256(dest)
            rec["bytes"] = dest.stat().st_size
            rec["status"] = "OK"
        else:
            rec["status"] = "FAILED (no file)"
    except Exception as e:  # honest capture: record, never hide
        rec["status"] = f"FAILED: {type(e).__name__}: {e}"
        if dest.exists():
            rec["sha256"] = sha256(dest)
            rec["bytes"] = dest.stat().st_size
            rec["status"] += " (STALE file on disk hashed above - do not trust)"
    return rec


def write_sources_md(records: list[dict]) -> None:
    lines = [
        "# SOURCES.md - data dictionary (GENERATED by data/pull.py - never hand-edit)",
        "",
        f"Generated: {date.today().isoformat()}. Store: `{STORE}` (git-ignored; needs its",
        "own off-machine backup). Raw data is never committed; this file is the",
        "documentation layer. Schema notes: macro series carry no session /",
        "adjustment / price-field variability - those fields are N/A throughout;",
        "timezone = vendor-native release calendar; bar interval = the stated",
        "frequency; date ranges are embedded in each file and pinned by its hash.",
        "",
        "## Frozen 17-sector panel map (DESIGN Section 14 + amendment 2026-07-13)",
        "",
        "NEVER edited after first hash. Roles: member-mfg (7), member-wholesale (7),",
        "member-retail (3) = 17 members; aux = pulled per manifest, non-member.",
        "",
        "| FRED id | role | series (FRED-verified title, abbreviated) |",
        "|---|---|---|",
    ]
    for sid, role, title in SECTOR_MAP:
        lines.append(f"| {sid} | {role} | {title} |")
    lines += [
        "",
        "## Pulled files",
        "",
        "| id | vendor | exact symbol / identifier | freq | used by | status | bytes | SHA256 | store path | replicator tolerance |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in records:
        lines.append(
            f"| {r['id']} | {r['vendor']} | {r['symbol']} | {r['freq']} | "
            f"{r['used_by']} | {r['status']} | {r.get('bytes','-')} | "
            f"`{r.get('sha256','-')}` | {r.get('store_path','-')} | {r['tol']} |")
    notes = [r for r in records if r.get("note")]
    if notes:
        lines += ["", "## Notes", ""]
        for r in notes:
            lines.append(f"- **{r['id']}**: {r['note']}")
    lines += [
        "", "## Omitted per manifest (conditional)", "",
        "E10 context (Fitch/ratingshistory, IMF GDD, FRED yield series, BIS) and",
        "E11 context (ETA 204/218/581, FDH 394, FRED UNRATE/PAYEMS/USREC/ICSA/CCSA)",
        "are pulled only if a committed analysis uses them (dated amendment),",
        "else omitted here per DESIGN Section 14.",
        "", "## Verification", "",
        "Re-run `python data\\pull.py --verify` to re-hash every file on disk; any",
        "hash drift vs the committed table is a red flag, never assumed away.", "",
    ]
    SOURCES_MD.write_text("\n".join(lines), encoding="ascii", newline="\n")


def main() -> int:
    verify_only = "--verify" in sys.argv
    only = sys.argv[sys.argv.index("--only") + 1] if "--only" in sys.argv else None
    RAW.mkdir(parents=True, exist_ok=True)
    records, failures = [], 0
    for src in SOURCES:
        if only and src["id"] != only:
            continue
        rec = pull_one(src, verify_only)
        records.append(rec)
        ok = rec["status"] == "OK" or rec["status"].startswith("DEFERRED")
        print(f"{'OK ' if ok else '!! '}{rec['id']:24s} {rec['status']}")
        if not ok:
            failures += 1
    if not only:
        write_sources_md(records)
        print(f"\nSOURCES.md regenerated ({SOURCES_MD}).")
    print(f"\n{len(records) - failures}/{len(records)} OK; {failures} need attention.")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
