"""e8_pricing.py - E8: pricing-mechanism analysis (asymmetry + the formula's value).

DESIGN.md Section 11 (pin 74c73ea165a7363c6714fe803fbe76b1) + amendments
2026-07-16 (classification), 16b (severity withdrawn), 16c (CIC complete, two-claim
structure), 16d (vendored set), 16e (NO RE-RUN; inputs; report forms).

THIS IS AN ANALYSIS, NOT A RE-EXECUTION (16e). It reads the source's own committed
artifact - 1,800 raw trial records - and computes the claims from it. That rests on
verification already earned, not on trust:
  * the source's pricing code clears ALL SEVEN CIC classes (16c). CIC-1 decisive:
    every published figure recomputes from these raw records at 13-21 sigma.
  * the code that produced the artifact is vendored at analysis/vendor/ and
    MD5-asserted by the suite (16d), so the audited bytes are the bytes on record.
  * the artifact itself is SHA256-registered in data/SOURCES.md and asserted by
    this script before any number is computed.
A re-run was measured and rejected: 19.04 s/trial => 55.5h to resolve a +13.01
effect, and powering to +13.01 is circular because +13.01 is itself a 0.60-sigma
reading. The finding is a BOUND, and their 50 seeds already carry it.

THE CENTRAL POINT - TWO CLAIMS, TWO COMPARISONS, NEVER SUBSTITUTED (16c).
E8's frozen purpose asks two questions in one sentence: "test whether THE
PERSISTENCE CALCULATION gives useful guidance on a second lever (price), AND
re-earn THE ASYMMETRIC FINDING (raises help under strain; cuts are uniformly
negative)." Those need different comparators, and the source's own code contains
both. From PricingPolicy's docstring: "Comparing against this baseline [naive]
ISOLATES THE VALUE OF THE FORMULA'S PERSISTENCE-DISCRIMINATION CAPABILITY beyond
the value of dynamic pricing in general."

  CLAIM A - the FORMULA's value:  phi_gated_* vs naive_reactive
      Both arms react to demand shifts. The persistence gate is the ONLY
      difference, so the difference IS the formula's contribution.
      Report form: ESTIMATE WITH UNCERTAINTY (a bound), never a verdict.
  CLAIM B - the ASYMMETRY of pricing reaction:  naive_reactive vs no_pricing
      Measures reacting at all. Nothing to do with the formula.
      Report form: VERDICT against the frozen assert/partial/drop rule.

v16 reports CLAIM B's number (+$10,142/period) as the evidence for CLAIM A ("whether
the formula gives useful guidance"). That is DISC-03, and it is this experiment's
central finding. This script computes both and reports them side by side so the
substitution is impossible to make.

SIGN CONVENTION: net_value = mean_revenue_per_period - cost_per_period, both already
per-period fields emitted by the source's runner over its 208-period post-warmup
window (CIC-2: cost range(52,260) and revenue [52:] share window AND divisor).
A POSITIVE paired difference means the first-named arm is BETTER (higher net value).

Writes analysis/outputs/e8_pricing.json.
"""

from __future__ import annotations

import hashlib
import json
import os
import pathlib
import statistics as st
import sys

_HERE = pathlib.Path(__file__).resolve().parent
OUT = _HERE / "outputs" / "e8_pricing.json"

STORE = pathlib.Path(os.environ.get(
    "EC_STORE", r"C:\Users\jaek9\Documents\LaggingTruth\The-Escalation-Cost"))
RAW = STORE / "raw" / "phase27"

# SHA256 registered in data/SOURCES.md (generated by data/pull.py --verify).
# Asserted before any number is computed: the hash pins the evidence. Every E8
# finding on record - CIC-1, DISC-03's +13.01 vs +10141.86, DISC-04's resolution,
# and the Claim A bound - was computed against THESE EXACT BYTES.
INPUTS = {
    "primary": ("aggregated_phase27_validation_50seed.json",
                "36d369ab0a0c743ce081a5d30dd7e4a0d3f7d58fbbfb76f0f5af6ddea47fa9b9"),
    "cap_18x": ("aggregated_phase27_capsweep_18x.json",
                "bbdd64f49f3be646ebcba04bfb02de748083b3dd95ce17e734792a9965093daa"),
    "cap_24x": ("aggregated_phase27_capsweep_24x.json",
                "034ade6ac6c1719ecdc41d4adcb9de1d3806718a804124bd0111b87acc90669d"),
    "cap_30x": ("aggregated_phase27_capsweep_30x.json",
                "e49d678a00e631ffeedf57b107f44b81ec25f0c2e5570a711da2a0416caabd7f"),
    "elas_05": ("aggregated_phase27_elasticity_05.json",
                "205ef1131d669794ff9f81af10cbe37e1eb0455b92de00daa6ce8b36ca0bfc53"),
    "elas_30": ("aggregated_phase27_elasticity_30.json",
                "18ed1c67bc876a765634859e8107cc5d6ae169999985586f5edbf40a767866da"),
}

# The five level-shift environments (the operator's scope). The four legacy
# persistence-only environments are controls and are NOT in scope: ar1_high and
# ar1_high_no_shift are the SAME no-shift control under two names (DISC-04).
UPWARD = ["level_shift_up_persistent", "low_phi_shift_up"]
DOWNWARD = ["level_shift_down_persistent", "low_phi_shift_down", "mid_phi_shift_down"]
ENVS = UPWARD + DOWNWARD

# The capacity-strained sustained-upward environment named by the frozen rule.
STRAINED_UP = "level_shift_up_persistent"

NAIVE, NOPRICE = "naive_reactive", "no_pricing"
GATED = ["phi_gated_asymmetric", "phi_gated_symmetric"]

Z95 = 1.959963984540054


def load(key: str) -> list:
    """Load an artifact, asserting its registered SHA256 FIRST.

    A hash mismatch is a hard stop, not a warning: if these are not the bytes
    SOURCES.md registered, nothing downstream means anything.
    """
    fname, want = INPUTS[key]
    p = RAW / fname
    if not p.exists():
        raise SystemExit(f"INPUT MISSING: {p}\nRun: python data\\pull.py --verify")
    got = hashlib.sha256(p.read_bytes()).hexdigest()
    if got != want:
        raise SystemExit(
            f"INPUT HASH MISMATCH for {fname}\n  registered: {want}\n  on disk   : {got}\n"
            f"These are not the bytes data/SOURCES.md registered. Stopping.")
    return json.loads(p.read_text())["trials"]


def net_by_seed(trials: list, env: str, scenario: str) -> dict:
    """Per-seed net value (revenue - cost), both already per-period fields."""
    return {t["trial_seed"]: t["mean_revenue_per_period"] - t["cost_per_period"]
            for t in trials
            if t["env"] == env and t["pricing_scenario"] == scenario
            and t.get("success")}


def paired(trials: list, env: str, arm: str, base: str) -> dict:
    """Paired per-seed difference (arm - base), with its uncertainty.

    Pairing is by trial_seed. The source's runner documents why this is valid:
    "Same seed across pricing scenarios produces identical baseline demand, which
    is what enables the within-simulation counterfactual analysis."
    """
    a, b = net_by_seed(trials, env, arm), net_by_seed(trials, env, base)
    common = sorted(set(a) & set(b))
    if len(common) < 2:
        return dict(n=len(common), mean=None, se=None, ci=None, resolved=False)
    d = [a[s] - b[s] for s in common]
    mean = st.mean(d)
    se = st.stdev(d) / (len(d) ** 0.5)
    return dict(n=len(common), mean=mean, se=se,
                ci=[mean - Z95 * se, mean + Z95 * se],
                sigma=(abs(mean) / se if se else None),
                resolved=bool(se and abs(mean) > Z95 * se),
                arms_identical=bool(all(a[s] == b[s] for s in common)))


def claim_b(trials: list) -> dict:
    """CLAIM B - the asymmetry of pricing REACTION: naive_reactive vs no_pricing.

    Verdict against the frozen rule: ASSERTED iff the value of raises is positive
    in the capacity-strained sustained-upward environment (95% CI excluding zero)
    AND the value of cuts is negative in EVERY downward environment tested.
    PARTIAL if raises hold but any cut-cell is non-negative ("uniformly negative"
    withdrawn). DROPPED if raises are not positive under strain.
    """
    cells = {e: paired(trials, e, NAIVE, NOPRICE) for e in ENVS}
    up = cells[STRAINED_UP]
    raises_ok = bool(up["resolved"] and up["mean"] > 0)
    cuts = {e: cells[e] for e in DOWNWARD}
    cuts_all_neg = all(c["resolved"] and c["mean"] < 0 for c in cuts.values())
    if not raises_ok:
        verdict = "DROPPED"
    elif cuts_all_neg:
        verdict = "ASSERTED"
    else:
        verdict = "PARTIAL"
    return dict(comparison=f"{NAIVE} vs {NOPRICE}", cells=cells, verdict=verdict,
                raises_positive_under_strain=raises_ok,
                cuts_negative_in_every_downward_env=cuts_all_neg,
                note=("Measures the value of REACTING TO DEMAND SHIFTS AT ALL. "
                      "This is NOT the formula's value - see claim_a. v16 reports "
                      "this comparison's number as the evidence for the formula "
                      "(DISC-03)."))


def claim_a(trials: list, b: dict) -> dict:
    """CLAIM A - the FORMULA's value: phi_gated_* vs naive_reactive.

    Report form is an ESTIMATE WITH UNCERTAINTY, not a verdict (16e). The question
    is "how large is it," and the answer is a BOUND. Powering to a verdict here
    would be circular: the headline cell's effect (+13.01) is itself a 0.60-sigma
    reading, so powering to detect it assumes it is real.

    Each cell's CI is reported in absolute terms AND as a percentage of that
    environment's own Claim B headline - which is what makes the attribution
    finding legible: the formula's ceiling against the number it is credited with.
    """
    out = {}
    for arm in GATED:
        cells = {}
        for e in ENVS:
            r = paired(trials, e, arm, NAIVE)
            head = b["cells"][e]["mean"]
            if r["ci"] and head:
                r["ci_pct_of_claim_b"] = [r["ci"][0] / abs(head) * 100,
                                          r["ci"][1] / abs(head) * 100]
                r["claim_b_headline"] = head
            cells[e] = r
        out[arm] = cells
    return dict(comparison=f"{GATED} vs {NAIVE}", by_arm=out,
                note=("The gate is the ONLY difference between these arms, so the "
                      "difference IS the formula's contribution. The source's own "
                      "PricingPolicy docstring: the naive baseline 'isolates the "
                      "value of the formula's persistence-discrimination "
                      "capability beyond the value of dynamic pricing in general.'"))


def robustness() -> dict:
    """Capacity and elasticity legs, from the source's own sweep artifacts.

    Qualifies the primary; NO standalone verdict. Reports Claim B (the reaction's
    value) per capacity/elasticity, which is what the source's own capacity-collapse
    claim is about.
    """
    legs = {}
    for key, label in (("cap_18x", "capacity 1.8x"), ("cap_24x", "capacity 2.4x"),
                       ("cap_30x", "capacity 3.0x"), ("elas_05", "elasticity 0.5"),
                       ("elas_30", "elasticity 3.0")):
        try:
            t = load(key)
        except SystemExit:
            legs[label] = {"status": "artifact unavailable"}
            continue
        legs[label] = {e: paired(t, e, NAIVE, NOPRICE) for e in ENVS}
    return legs


def main() -> None:
    print("E8 pricing analysis (ANALYSIS of the source's verified artifact; no re-run)")
    trials = load("primary")
    print(f"  primary artifact: {len(trials)} raw trials, SHA256 asserted OK")

    b = claim_b(trials)
    a = claim_a(trials, b)
    rob = robustness()

    out = dict(experiment="E8", date="2026-07-16",
               design_pin="74c73ea165a7363c6714fe803fbe76b1",
               build=("ANALYSIS of the source's committed artifact (DESIGN 16e); "
                      "no re-execution. Source code CIC-cleared on all seven "
                      "classes (16c); vendored closure MD5-asserted (16d); input "
                      "SHA256-registered in data/SOURCES.md."),
               report_form=("Claim A: ESTIMATE WITH UNCERTAINTY (a bound), no "
                            "verdict. Claim B: VERDICT against the frozen rule. "
                            "Robustness: stability statement, no verdict."),
               spec=dict(environments=ENVS, upward=UPWARD, downward=DOWNWARD,
                         strained_up=STRAINED_UP, inputs={k: v[0] for k, v in INPUTS.items()},
                         sign_convention="positive = first-named arm is BETTER"),
               claim_a=a, claim_b=b, robustness=rob)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2))

    print()
    print("CLAIM B - the asymmetry of pricing REACTION (naive vs no_pricing)")
    print(f"  VERDICT: {b['verdict']}")
    for e in ENVS:
        c = b["cells"][e]
        print("    %-30s %+10.2f  [%+9.2f,%+9.2f]  %5.1f sigma  %s"
              % (e, c["mean"], c["ci"][0], c["ci"][1], c["sigma"],
                 "RESOLVED" if c["resolved"] else "unresolved"))
    print()
    print("CLAIM A - the FORMULA's value (phi_gated_asymmetric vs naive)")
    print("  reported as a BOUND, with each CI as a %% of that env's Claim B headline")
    for e in ENVS:
        c = a["by_arm"]["phi_gated_asymmetric"][e]
        pct = c.get("ci_pct_of_claim_b")
        print("    %-30s %+8.2f  [%+8.2f,%+8.2f]  %4.1f sig %-10s  = [%+6.2f%%,%+6.2f%%] of %+10.2f"
              % (e, c["mean"], c["ci"][0], c["ci"][1], c["sigma"],
                 "RESOLVED" if c["resolved"] else "unresolved",
                 pct[0], pct[1], c["claim_b_headline"]))
    hc = a["by_arm"]["phi_gated_asymmetric"][STRAINED_UP]
    print()
    print("  THE HEADLINE CELL (%s):" % STRAINED_UP)
    print("    reacting at all (Claim B) = %+.2f/period" % b["cells"][STRAINED_UP]["mean"])
    print("    the formula   (Claim A)   = [%+.2f, %+.2f]  -> at most %.2f%% of it"
          % (hc["ci"][0], hc["ci"][1], hc["ci_pct_of_claim_b"][1]))


if __name__ == "__main__":
    main()
