"""render_paper.py - substitute {{LB-id}} tokens with ledger values.

The committed renderer required by the Standard's Phase-4 rule that no figure
is ever retyped by hand: every load-bearing number in the manuscript appears as
a {{LB-id}} token in the SOURCE (paper/the-escalation-cost.md, the authoritative
file that verify.py polices) and is substituted here, mechanically, from
analysis/claims.lock (itself produced only by the committed builder).

Rendering rules (deterministic, no rounding - the ledger's stored precision is
the paper's precision; presentational rounding is a prose decision made by
changing what the builder stores, never by this script):
  str   -> as-is
  bool  -> "true" / "false"
  int   -> decimal string
  float -> repr(value) (shortest round-trip representation)
  dict  -> compact JSON, sorted keys (used by interval-style rows)
  null  -> "n/a" (a committed artifact's honest not-computed marker - e.g.
           calm rho for the explosive sovereign countries, where the
           diagnostic's own precondition fails; the ledger stores the null)

Fails loud (exit 2) if the manuscript contains a token with no ledger row or
any {{...}} that is not a ledger token. The reverse direction (every ledger id
placed in the paper) is verify.py's job; the renderer re-asserts it anyway.

Output: paper/the-escalation-cost.rendered.md (never hand-edited; regenerated
on every change to the source or the ledger).
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "paper" / "the-escalation-cost.md"
LOCK = ROOT / "analysis" / "claims.lock"
OUT = ROOT / "paper" / "the-escalation-cost.rendered.md"


def fmt(v) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return v
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, dict):
        return json.dumps(v, sort_keys=True, separators=(", ", ": "))
    raise TypeError(f"unrenderable ledger value type: {type(v).__name__}")


def main() -> int:
    rows = json.loads(LOCK.read_text(encoding="utf-8"))["rows"]
    values = {r["id"]: r["expected"] for r in rows}
    text = SRC.read_text(encoding="utf-8")

    problems = []
    tokens = re.findall(r"\{\{([^{}]+)\}\}", text)
    for t in sorted(set(tokens)):
        if t not in values:
            problems.append(f"token has no ledger row: {{{{{t}}}}}")
    for i in sorted(values):
        if ("{{%s}}" % i) not in text:
            problems.append(f"ledger id never placed in source: {i}")
    if problems:
        for p in problems:
            print(f"RENDER RED: {p}")
        return 2

    def sub(m: re.Match) -> str:
        return fmt(values[m.group(1)])

    rendered = re.sub(r"\{\{([^{}]+)\}\}", sub, text)
    header = ("<!-- RENDERED FILE - generated by analysis/render_paper.py from "
              "the token source and analysis/claims.lock; NEVER hand-edited. -->\n")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header + rendered)
    n = len(tokens)
    print(f"RENDER GREEN: {n} token occurrences ({len(set(tokens))} distinct ids) "
          f"substituted; output {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
